apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "env-${name}"
  labels:
    secretType: env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "env-${name}"
    kind: SecretStore
  target:
    name: "env-${name}"
    deletionPolicy: "Delete"
  dataFrom:
  - extract:
      key: "tenants/t-${tenantname}/configs/base/${name}/env"
