apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "config-${name}"
  labels:
    secretType: config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "config-${name}"
    kind: SecretStore
  target:
    name: "config-${name}"
    deletionPolicy: "Delete"
  data:
  - secretKey: base.yaml
    remoteRef:
      key: "tenants/t-${tenantname}/configs/base/${name}/config"
      property: config.yaml
