apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "${namesuffix}"
commonLabels:
  toolkit.fluxcd.io/tenant: "${tenantname}"
resources:
- deployment.yaml
- externalsecret-config.yaml
- externalsecret-env.yaml
- secretstore.yaml
- serviceaccount.yaml
- service.yaml
- virtualservice.yaml
