tls:
  server:
    certificate:
      path: "tls/server/cert/cert.pem"
    key:
      path: "tls/server/key/key.pem"
  client:
    ca:
      path: "tls/client/ca/ca.pem"
google:
  storage:
    bucket:
      name: bucket
db:
  url: ""
  name: ""
server:
  port: 8081
