tls:
  generate: true
  ca:
    certificate:
      o: pauwels
      ou: ca
      cn: storer
      expires_in: 365
      path: "tls/server/cert/ca.pem"
    key:
      path: "tls/server/key/ca.pem"
  server:
    certificate:
      o: pauwels
      ou: tls
      cn: storer
      expires_in: 365
      path: "tls/server/cert/server.pem"
    key:
      path: "tls/server/key/server.pem"
google:
  storage:
    bucket:
      name: default_bucket_hw
db:
  url: ""
  name: ""
server:
  port: 8081
google:
  storage:
    bucket:
      name: ""
